services:
  db:
    image: postgres:16
    container_name: ordo_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ordo_db_data:/var/lib/postgresql/data

volumes:
  ordo_db_data:
